### ISSUE TITLE
Lab HW Submission

### ISSUE THREAD

**Issue by thomhouseholder** [ga-dc/wdi_radio_lab#12]
Cloned instead of forking at the beginning of the lab.  The repo is https://github.com/thomhouseholder/wdi_radio_api_thom.

This was a good project, lots of fun and a good learning experience.  Want to implement more CRUD to manipulate data.

**Comment by jshawl** [comment]
:+1: code looks great! Let me know if you'd like specific feedback on anything or would like to pair after break!
