### ISSUE TITLE
HW submission

### ISSUE THREAD

**Issue by Cajam** [ga-dc/wdi_radio_lab#14]
Having issues getting the signup to work, with a $$hashkey error. 

https://github.com/Cajam/wdi_radio_lab

**Comment by jshawl** [comment]
:+1: looks like `$scope` and `$state` are reversed here - https://github.com/Cajam/wdi_radio_lab/blob/7983c2140ac49771b22ea6b10c7b8b66e3ffccd0/js/sessions.controller.js#L4 I think this is causing the issue!

Let me know if you'd like to pair on this after break
