### ISSUE TITLE
Joe GZ, Eric S, Josh C radio lab

### ISSUE THREAD

**Issue by joe-gz** [ga-dc/wdi_radio_lab#17]
https://github.com/joe-gz/ejj_radio/tree/master

comfort: 4 until the music player. we couldnt get that yet
completeness: 3.5 because of the music.

**Comment by joe-gz** [comment]
worked with Eric Stennet and Josh Cohen

**Comment by ebirving** [comment]
Great work, guys! Creative and functional -- just the combination you want when squaring off against a hungry raptor. :+1:
