### ISSUE TITLE
Mia G RadioLab Submission

### ISSUE THREAD

**Issue by mcgrodsky** [ga-dc/wdi_radio_lab#21]
Pair programmed for the first bit. This is my branch i worked with:

https://github.com/timothytgregg/radiolab/tree/custom_directives_refactor

Comfort: 4/5 - really liking angular. Think it's awesome to have all this functionality in the html and excited to learn more about custom directives

complete: 5/5. completed all expectations, got some crud functionality (everything but create) and user auth. Very close to getting songs to play, but not quite there.

**Comment by jshawl** [comment]
:+1: As I commented on tim's issue, code looks great! Let me know if you'd like specific feedback on anything.
