### ISSUE TITLE
Jmoon's lab submission

### ISSUE THREAD

**Issue by mooniker** [ga-dc/wdi_radio_lab#25]
I also worked with Markham on Wednesday, so if he submits his and it's any good, then you can say I was a part of that.

That said, I was out sick yesterday and missed the lesson on custom directives. (Couldn't find a screencast.) I spent today just reimplementing essentially what Markham and I had already accomplished on Wednesday, but I tried changing up the organization of the files and adding in what I think is a custom directive for song.

I find the debugging extremely difficult with Angular.

https://github.com/mooniker/radiolab

**Comment by andrewsunglaekim** [comment]
Yes, debugging angular is extremely frustrating.  If you use it enough, it becomes a bit less cryptic. Just think of custom directives as partials or templates. You can actually pass your viewmodel into them to have direct access to anything you defined in your controller. It makes angular really powerful allowing the framework to focus on features.
