### ISSUE TITLE
Ly's Lab 

### ISSUE THREAD

**Issue by Ly900** [ga-dc/wdi_radio_lab#33]
**Comfort:** 3.7
**Completeness:** 4? 

I think CRUD was a bonus so I did not include that in my completeness number. 

I misunderstood the lab directions and created the app from scratch so did not fork and thus not able to do a pull request. Below are the links to my repo:

**WDI Radio Rails API:** https://github.com/Ly900/wdi_radio_api
**WDI Radio App:** https://github.com/Ly900/wdi_radio_lab

**Comment by andrewsunglaekim** [comment]
great! always good practice to start from scratch. What you have looks pretty good. I encourage you to figure out all the CRUD functionality. It will allow you to better understand the core concepts of angular. :+1:
